// Tax constants for 2026
// (c) Jacob Lundberg 2013-2022, update Erik Bengtzboe 2024-2026

/**
 * Tax year configuration for 2026.
 * All monetary values in SEK.
 */
export const TAX_YEAR_2026 = {
  /** Prisbasbelopp */
  PBB: 59200,
  /** Inkomstbasbelopp */
  IBB: 83400,
  /** Arbetsgivaravgift */
  AGA: 0.3142,
  /** Default begravningsavgift rate */
  BURIAL_FEE_DEFAULT: 0.00292,
  /** Stockholm begravningsavgift rate */
  BURIAL_FEE_STOCKHOLM: 0.0007,
  /** Statlig inkomstskatt rate */
  STATE_TAX_RATE: 0.20,
  /** Allmän pensionsavgift rate */
  PENSION_RATE: 0.07,
  /** Viktad moms (weighted VAT across population average) */
  WEIGHTED_VAT: 0.184,
  /** Public service-avgift rate */
  PUBLIC_SERVICE_RATE: 0.01,
  /** Skiktgräns for statlig inkomstskatt */
  BRYTPUNKT: 660400,
  /** Max public service-avgift */
  PUBLIC_SERVICE_MAX: 1184,
  /** IBB multiplier for public service threshold */
  PUBLIC_SERVICE_THRESHOLD_MULTIPLIER: 1.42,
  /** Skattereduktion för boende i vissa områden */
  REGIONAL_REDUCTION_AMOUNT: 1675,
  /** Skattereduktion för förvärvsinkomst */
  EMPLOYMENT_INCOME_REDUCTION: {
    LOWER: 40000,
    UPPER: 240000,
    RATE: 0.0075,
    MAX: 1500,
  },
  /** Stockholm municipal tax rate (used for burial fee detection) */
  STOCKHOLM_RATE: 0.3055,
};

/**
 * Grundavdrag brackets for 2026.
 * Each tier defines the PBB-multiple range and how to compute the deduction.
 * - Tiers with `coefficient`: deduction = ceil(coefficient * PBB / 100) * 100
 * - Tiers with `baseCoefficient` + `incomeCoefficient`: deduction = ceil((baseCoefficient * PBB + incomeCoefficient * income) / 100) * 100
 */
export const GRUNDAVDRAG_BRACKETS = [
  { minPBB: 0, maxPBB: 0.99, coefficient: 0.423 },
  { minPBB: 0.99, maxPBB: 2.72, baseCoefficient: 0.225, incomeCoefficient: 0.2 },
  { minPBB: 2.72, maxPBB: 3.11, coefficient: 0.770 },
  { minPBB: 3.11, maxPBB: 7.88, baseCoefficient: 1.081, incomeCoefficient: -0.1 },
  { minPBB: 7.88, maxPBB: Infinity, coefficient: 0.293 },
];

/**
 * Jobbskatteavdrag brackets for 2026.
 * Each tier defines how JSA is computed based on PBB-multiple ranges.
 * The `compute` description maps to the original formula.
 */
export const JOBBSKATTEAVDRAG_BRACKETS = [
  { minPBB: 0, maxPBB: 0.91, type: 'linear' },
  { minPBB: 0.91, maxPBB: 3.24, baseMultiplier: 0.91, slope: 0.3874 },
  { minPBB: 3.24, maxPBB: 8.08, basePBB: 1.813, lowerPBB: 3.24, slope: 0.251 },
  { minPBB: 8.08, maxPBB: Infinity, capPBB: 3.027 },
];

/**
 * All 291 municipalities (including Riksgenomsnitt) with their tax rates.
 * Sorted alphabetically by name (Riksgenomsnitt first).
 */
export const MUNICIPALITIES = [
  { name: 'Riksgenomsnitt', rate: 32.38 },
  { name: 'Ale', rate: 32.80 },
  { name: 'Alingsås', rate: 32.84 },
  { name: 'Alvesta', rate: 33.42 },
  { name: 'Aneby', rate: 33.85 },
  { name: 'Arboga', rate: 33.29 },
  { name: 'Arjeplog', rate: 34.84 },
  { name: 'Arvidsjaur', rate: 34.14 },
  { name: 'Arvika', rate: 34.03 },
  { name: 'Askersund', rate: 34.15 },
  { name: 'Avesta', rate: 33.95 },
  { name: 'Bengtsfors', rate: 34.40 },
  { name: 'Berg', rate: 34.22 },
  { name: 'Bjurholm', rate: 35.00 },
  { name: 'Bjuv', rate: 32.17 },
  { name: 'Boden', rate: 33.94 },
  { name: 'Bollebygd', rate: 33.07 },
  { name: 'Bollnäs', rate: 33.37 },
  { name: 'Borgholm', rate: 33.44 },
  { name: 'Borlänge', rate: 34.40 },
  { name: 'Borås', rate: 32.79 },
  { name: 'Botkyrka', rate: 32.23 },
  { name: 'Boxholm', rate: 33.37 },
  { name: 'Bromölla', rate: 33.74 },
  { name: 'Bräcke', rate: 35.09 },
  { name: 'Burlöv', rate: 31.27 },
  { name: 'Båstad', rate: 31.41 },
  { name: 'Dals-Ed', rate: 34.69 },
  { name: 'Danderyd', rate: 30.58 },
  { name: 'Degerfors', rate: 35.30 },
  { name: 'Dorotea', rate: 35.65 },
  { name: 'Eda', rate: 34.55 },
  { name: 'Ekerö', rate: 31.45 },
  { name: 'Eksjö', rate: 34.02 },
  { name: 'Emmaboda', rate: 33.82 },
  { name: 'Enköping', rate: 33.05 },
  { name: 'Eskilstuna', rate: 32.85 },
  { name: 'Eslöv', rate: 31.72 },
  { name: 'Essunga', rate: 33.05 },
  { name: 'Fagersta', rate: 32.99 },
  { name: 'Falkenberg', rate: 32.50 },
  { name: 'Falköping', rate: 33.43 },
  { name: 'Falun', rate: 34.05 },
  { name: 'Filipstad', rate: 34.55 },
  { name: 'Finspång', rate: 33.70 },
  { name: 'Flen', rate: 33.10 },
  { name: 'Forshaga', rate: 34.63 },
  { name: 'Färgelanda', rate: 34.39 },
  { name: 'Gagnef', rate: 34.27 },
  { name: 'Gislaved', rate: 33.75 },
  { name: 'Gnesta', rate: 32.95 },
  { name: 'Gnosjö', rate: 34.00 },
  { name: 'Gotland', rate: 33.60 },
  { name: 'Grums', rate: 34.78 },
  { name: 'Grästorp', rate: 33.47 },
  { name: 'Gullspång', rate: 33.97 },
  { name: 'Gällivare', rate: 33.89 },
  { name: 'Gävle', rate: 33.77 },
  { name: 'Göteborg', rate: 32.60 },
  { name: 'Götene', rate: 33.60 },
  { name: 'Habo', rate: 33.93 },
  { name: 'Hagfors', rate: 34.30 },
  { name: 'Hallsberg', rate: 33.85 },
  { name: 'Hallstahammar', rate: 32.69 },
  { name: 'Halmstad', rate: 32.38 },
  { name: 'Hammarö', rate: 35.05 },
  { name: 'Haninge', rate: 31.28 },
  { name: 'Haparanda', rate: 33.84 },
  { name: 'Heby', rate: 34.21 },
  { name: 'Hedemora', rate: 34.15 },
  { name: 'Helsingborg', rate: 31.39 },
  { name: 'Herrljunga', rate: 33.62 },
  { name: 'Hjo', rate: 33.48 },
  { name: 'Hofors', rate: 34.37 },
  { name: 'Huddinge', rate: 31.71 },
  { name: 'Hudiksvall', rate: 33.12 },
  { name: 'Hultsfred', rate: 33.77 },
  { name: 'Hylte', rate: 33.85 },
  { name: 'Håbo', rate: 33.30 },
  { name: 'Hällefors', rate: 34.35 },
  { name: 'Härjedalen', rate: 34.17 },
  { name: 'Härnösand', rate: 34.63 },
  { name: 'Härryda', rate: 31.98 },
  { name: 'Hässleholm', rate: 32.38 },
  { name: 'Höganäs', rate: 30.91 },
  { name: 'Högsby', rate: 34.07 },
  { name: 'Hörby', rate: 32.26 },
  { name: 'Höör', rate: 32.63 },
  { name: 'Jokkmokk', rate: 34.29 },
  { name: 'Järfälla', rate: 31.52 },
  { name: 'Jönköping', rate: 33.40 },
  { name: 'Kalix', rate: 33.89 },
  { name: 'Kalmar', rate: 33.67 },
  { name: 'Karlsborg', rate: 32.80 },
  { name: 'Karlshamn', rate: 33.80 },
  { name: 'Karlskoga', rate: 34.30 },
  { name: 'Karlskrona', rate: 33.69 },
  { name: 'Karlstad', rate: 33.55 },
  { name: 'Katrineholm', rate: 32.95 },
  { name: 'Kil', rate: 34.63 },
  { name: 'Kinda', rate: 33.00 },
  { name: 'Kiruna', rate: 34.39 },
  { name: 'Klippan', rate: 31.93 },
  { name: 'Knivsta', rate: 32.62 },
  { name: 'Kramfors', rate: 34.43 },
  { name: 'Kristianstad', rate: 32.64 },
  { name: 'Kristinehamn', rate: 34.25 },
  { name: 'Krokom', rate: 33.87 },
  { name: 'Kumla', rate: 33.84 },
  { name: 'Kungsbacka', rate: 32.58 },
  { name: 'Kungsör', rate: 32.91 },
  { name: 'Kungälv', rate: 32.92 },
  { name: 'Kävlinge', rate: 29.59 },
  { name: 'Köping', rate: 33.04 },
  { name: 'Laholm', rate: 32.80 },
  { name: 'Landskrona', rate: 31.42 },
  { name: 'Laxå', rate: 35.00 },
  { name: 'Lekeberg', rate: 33.73 },
  { name: 'Leksand', rate: 33.80 },
  { name: 'Lerum', rate: 32.03 },
  { name: 'Lessebo', rate: 33.81 },
  { name: 'Lidingö', rate: 29.67 },
  { name: 'Lidköping', rate: 32.74 },
  { name: 'Lilla Västby', rate: 33.85 },
  { name: 'Lindesberg', rate: 34.60 },
  { name: 'Linköping', rate: 31.75 },
  { name: 'Ljungby', rate: 33.07 },
  { name: 'Ljusdal', rate: 33.87 },
  { name: 'Ljusnarsberg', rate: 33.80 },
  { name: 'Lomma', rate: 30.72 },
  { name: 'Ludvika', rate: 34.05 },
  { name: 'Luleå', rate: 33.84 },
  { name: 'Lund', rate: 32.42 },
  { name: 'Lycksele', rate: 34.90 },
  { name: 'Lysekil', rate: 33.94 },
  { name: 'Malmö', rate: 32.42 },
  { name: 'Malung-Sälen', rate: 34.45 },
  { name: 'Malå', rate: 35.20 },
  { name: 'Mariestad', rate: 32.74 },
  { name: 'Mark', rate: 32.99 },
  { name: 'Markaryd', rate: 33.31 },
  { name: 'Mellerud', rate: 34.08 },
  { name: 'Mjölby', rate: 33.45 },
  { name: 'Mora', rate: 34.32 },
  { name: 'Motala', rate: 33.25 },
  { name: 'Mullsjö', rate: 34.10 },
  { name: 'Munkedal', rate: 34.86 },
  { name: 'Munkfors', rate: 34.30 },
  { name: 'Mölndal', rate: 31.99 },
  { name: 'Mönsterås', rate: 34.07 },
  { name: 'Mörbylånga', rate: 34.07 },
  { name: 'Nacka', rate: 30.11 },
  { name: 'Nora', rate: 34.55 },
  { name: 'Norberg', rate: 33.54 },
  { name: 'Nordanstig', rate: 34.02 },
  { name: 'Nordmaling', rate: 35.10 },
  { name: 'Norrköping', rate: 33.30 },
  { name: 'Norrtälje', rate: 32.05 },
  { name: 'Norsjö', rate: 35.20 },
  { name: 'Nybro', rate: 34.19 },
  { name: 'Nykvarn', rate: 32.30 },
  { name: 'Nyköping', rate: 32.25 },
  { name: 'Nynäshamn', rate: 32.18 },
  { name: 'Nässjö', rate: 34.30 },
  { name: 'Ockelbo', rate: 34.27 },
  { name: 'Olofström', rate: 33.75 },
  { name: 'Orsa', rate: 34.30 },
  { name: 'Orust', rate: 33.69 },
  { name: 'Osby', rate: 33.99 },
  { name: 'Oskarshamn', rate: 34.21 },
  { name: 'Ovanåker', rate: 33.37 },
  { name: 'Oxelösund', rate: 33.05 },
  { name: 'Pajala', rate: 34.74 },
  { name: 'Partille', rate: 31.36 },
  { name: 'Perstorp', rate: 31.99 },
  { name: 'Piteå', rate: 33.59 },
  { name: 'Ragunda', rate: 34.92 },
  { name: 'Robertsfors', rate: 35.00 },
  { name: 'Ronneby', rate: 33.68 },
  { name: 'Rättvik', rate: 33.80 },
  { name: 'Sala', rate: 33.19 },
  { name: 'Salem', rate: 32.00 },
  { name: 'Sandviken', rate: 33.12 },
  { name: 'Sigtuna', rate: 31.83 },
  { name: 'Simrishamn', rate: 31.69 },
  { name: 'Sjöbo', rate: 32.10 },
  { name: 'Skara', rate: 33.38 },
  { name: 'Skellefteå', rate: 34.45 },
  { name: 'Skinnskatteberg', rate: 33.34 },
  { name: 'Skurup', rate: 31.60 },
  { name: 'Skövde', rate: 33.09 },
  { name: 'Smedjebacken', rate: 34.44 },
  { name: 'Sollefteå', rate: 34.68 },
  { name: 'Sollentuna', rate: 30.45 },
  { name: 'Solna', rate: 29.70 },
  { name: 'Sorsele', rate: 35.45 },
  { name: 'Sotenäs', rate: 33.47 },
  { name: 'Staffanstorp', rate: 30.12 },
  { name: 'Stenungsund', rate: 33.12 },
  { name: 'Stockholm', rate: 30.55 },
  { name: 'Storfors', rate: 34.98 },
  { name: 'Storuman', rate: 34.95 },
  { name: 'Strängnäs', rate: 32.50 },
  { name: 'Strömstad', rate: 33.39 },
  { name: 'Strömsund', rate: 34.92 },
  { name: 'Sundbyberg', rate: 31.58 },
  { name: 'Sundsvall', rate: 33.88 },
  { name: 'Sunne', rate: 33.75 },
  { name: 'Surahammar', rate: 33.19 },
  { name: 'Svalöv', rate: 31.92 },
  { name: 'Svedala', rate: 31.42 },
  { name: 'Svenljunga', rate: 33.53 },
  { name: 'Säffle', rate: 33.80 },
  { name: 'Säter', rate: 34.30 },
  { name: 'Sävsjö', rate: 33.68 },
  { name: 'Söderhamn', rate: 33.17 },
  { name: 'Söderköping', rate: 33.53 },
  { name: 'Södertälje', rate: 32.38 },
  { name: 'Sölvesborg', rate: 33.86 },
  { name: 'Tanum', rate: 33.04 },
  { name: 'Tibro', rate: 33.19 },
  { name: 'Tidaholm', rate: 33.55 },
  { name: 'Tierp', rate: 33.00 },
  { name: 'Timrå', rate: 34.38 },
  { name: 'Tingsryd', rate: 34.00 },
  { name: 'Tjörn', rate: 33.19 },
  { name: 'Tomelilla', rate: 31.79 },
  { name: 'Torsby', rate: 34.30 },
  { name: 'Torsås', rate: 33.79 },
  { name: 'Tranemo', rate: 32.98 },
  { name: 'Tranås', rate: 33.77 },
  { name: 'Trelleborg', rate: 31.58 },
  { name: 'Trollhättan', rate: 33.84 },
  { name: 'Trosa', rate: 32.03 },
  { name: 'Tyresö', rate: 31.83 },
  { name: 'Täby', rate: 29.88 },
  { name: 'Töreboda', rate: 33.20 },
  { name: 'Uddevalla', rate: 33.64 },
  { name: 'Ulricehamn', rate: 32.53 },
  { name: 'Umeå', rate: 34.65 },
  { name: 'Upplands Västby', rate: 31.75 },
  { name: 'Upplands-Bro', rate: 31.73 },
  { name: 'Uppsala', rate: 32.85 },
  { name: 'Uppvidinge', rate: 33.80 },
  { name: 'Vadstena', rate: 34.35 },
  { name: 'Vaggeryd', rate: 33.25 },
  { name: 'Valdemarsvik', rate: 34.03 },
  { name: 'Vallentuna', rate: 31.23 },
  { name: 'Vansbro', rate: 34.28 },
  { name: 'Vara', rate: 33.25 },
  { name: 'Varberg', rate: 31.73 },
  { name: 'Vaxholm', rate: 31.63 },
  { name: 'Vellinge', rate: 29.68 },
  { name: 'Vetlanda', rate: 33.77 },
  { name: 'Vilhelmina', rate: 35.50 },
  { name: 'Vimmerby', rate: 34.22 },
  { name: 'Vindeln', rate: 35.20 },
  { name: 'Vingåker', rate: 33.50 },
  { name: 'Vårgårda', rate: 33.09 },
  { name: 'Vänersborg', rate: 33.69 },
  { name: 'Vännäs', rate: 35.20 },
  { name: 'Värmdö', rate: 31.31 },
  { name: 'Värnamo', rate: 33.28 },
  { name: 'Västervik', rate: 33.02 },
  { name: 'Västerås', rate: 31.24 },
  { name: 'Växjö', rate: 32.19 },
  { name: 'Ydre', rate: 34.10 },
  { name: 'Ystad', rate: 31.29 },
  { name: 'Åmål', rate: 33.94 },
  { name: 'Ånge', rate: 34.62 },
  { name: 'Åre', rate: 33.92 },
  { name: 'Årjäng', rate: 34.25 },
  { name: 'Åsele', rate: 35.45 },
  { name: 'Åstorp', rate: 31.47 },
  { name: 'Åtvidaberg', rate: 33.94 },
  { name: 'Älmhult', rate: 33.86 },
  { name: 'Älvdalen', rate: 34.77 },
  { name: 'Älvkarleby', rate: 34.40 },
  { name: 'Älvsbyn', rate: 33.79 },
  { name: 'Ängelholm', rate: 31.35 },
  { name: 'Öckerö', rate: 33.04 },
  { name: 'Ödeshög', rate: 33.95 },
  { name: 'Örebro', rate: 33.65 },
  { name: 'Örkelljunga', rate: 30.24 },
  { name: 'Örnsköldsvik', rate: 33.85 },
  { name: 'Östersund', rate: 33.72 },
  { name: 'Österåker', rate: 28.93 },
  { name: 'Östhammar', rate: 33.30 },
  { name: 'Östra Västby', rate: 32.17 },
  { name: 'Överkalix', rate: 34.14 },
  { name: 'Övertorneå', rate: 33.84 },
];

/**
 * Municipalities qualifying for regional residence tax reduction.
 * Bug fix: original had "Filipstads" but dropdown has "Filipstad".
 */
export const REGIONAL_REDUCTION_MUNICIPALITIES = new Set([
  'Avesta', 'Gagnef', 'Hedemora', 'Leksand', 'Ludvika', 'Malung-Sälen',
  'Mora', 'Orsa', 'Rättvik', 'Smedjebacken', 'Säter', 'Vansbro', 'Älvdalen',
  'Bollnäs', 'Hudiksvall', 'Ljusdal', 'Nordanstig', 'Ockelbo', 'Ovanåker', 'Söderhamn',
  'Berg', 'Bräcke', 'Härjedalen', 'Krokom', 'Ragunda', 'Strömsund', 'Åre', 'Östersund',
  'Arjeplog', 'Arvidsjaur', 'Boden', 'Gällivare', 'Haparanda', 'Jokkmokk', 'Kalix',
  'Kiruna', 'Pajala', 'Piteå', 'Älvsbyn', 'Överkalix', 'Övertorneå',
  'Arvika', 'Eda', 'Filipstad', 'Hagfors', 'Munkfors', 'Storfors', 'Sunne', 'Säffle',
  'Torsby', 'Årjäng',
  'Bjurholm', 'Dorotea', 'Lycksele', 'Malå', 'Nordmaling', 'Norsjö', 'Robertsfors',
  'Skellefteå', 'Sorsele', 'Storuman', 'Vilhelmina', 'Vindeln', 'Vännäs', 'Åsele',
  'Härnösand', 'Kramfors', 'Sollefteå', 'Timrå', 'Ånge', 'Örnsköldsvik',
  'Bengtsfors', 'Dals-Ed', 'Färgelanda', 'Mellerud', 'Åmål',
]);
