// Skattekonstanter för 2026
// (c) Jacob Lundberg 2013-2022, uppdatering Erik Bengtzboe 2024-2026

/**
 * Inkomstårkonfiguration för 2026.
 * Alla belopp i SEK.
 */
export const INKOMSTÅR_2026 = {
  /** Prisbasbelopp */
  PBB: 59200,
  /** Inkomstbasbelopp */
  IBB: 83400,
  /** Arbetsgivaravgift */
  AGA: 0.3142,
  /** Standard begravningsavgift */
  BEGRAVNINGSAVGIFT_STANDARD: 0.00292,
  /** Begravningsavgift Stockholm */
  BEGRAVNINGSAVGIFT_STOCKHOLM: 0.0007,
  /** Statlig inkomstskattesats */
  STATLIG_SKATTESATS: 0.20,
  /** Allmän pensionsavgiftssats */
  PENSIONSAVGIFT: 0.07,
  /** Viktad moms (genomsnitt i befolkningen) */
  VIKTAD_MOMS: 0.184,
  /** Public service-avgiftssats */
  PUBLIC_SERVICE_AVGIFT: 0.01,
  /** Skiktgräns för statlig inkomstskatt */
  BRYTPUNKT: 660400,
  /** Max public service-avgift */
  PUBLIC_SERVICE_MAX: 1184,
  /** IBB-multiplikator för public service-tröskel */
  PUBLIC_SERVICE_TRÖSKELMULTIPLIKATOR: 1.42,
  /** Skattereduktion för boende i vissa områden */
  REGIONAL_SKATTEREDUKTION_BELOPP: 1675,
  /** Skattereduktion för förvärvsinkomst */
  SKATTEREDUKTION_FÖRVÄRVSINKOMST: {
    UNDRE: 40000,
    ÖVRE: 240000,
    SATS: 0.0075,
    MAX: 1500,
  },
  /** Stockholms kommunalskattesats (används för begravningsavgift) */
  STOCKHOLMS_SKATTESATS: 0.3055,
};

/**
 * Grundavdragsintervall för 2026.
 * Varje nivå definierar PBB-multipelsintervallet och hur avdraget beräknas.
 * - Nivåer med `koefficient`: avdrag = ceil(koefficient * PBB / 100) * 100
 * - Nivåer med `basKoefficient` + `inkomstKoefficient`: avdrag = ceil((basKoefficient * PBB + inkomstKoefficient * inkomst) / 100) * 100
 */
export const GRUNDAVDRAG_INTERVALL = [
  { minPBB: 0, maxPBB: 0.99, koefficient: 0.423 },
  { minPBB: 0.99, maxPBB: 2.72, basKoefficient: 0.225, inkomstKoefficient: 0.2 },
  { minPBB: 2.72, maxPBB: 3.11, koefficient: 0.770 },
  { minPBB: 3.11, maxPBB: 7.88, basKoefficient: 1.081, inkomstKoefficient: -0.1 },
  { minPBB: 7.88, maxPBB: Infinity, koefficient: 0.293 },
];

/**
 * Jobbskatteavdragsintervall för 2026.
 * Varje nivå definierar hur jobbskatteavdraget beräknas baserat på PBB-multipelsintervall.
 */
export const JOBBSKATTEAVDRAG_INTERVALL = [
  { minPBB: 0, maxPBB: 0.91, typ: 'linjär' },
  { minPBB: 0.91, maxPBB: 3.24, basMultiplikator: 0.91, lutning: 0.3874 },
  { minPBB: 3.24, maxPBB: 8.08, basPBB: 1.813, undrePBB: 3.24, lutning: 0.251 },
  { minPBB: 8.08, maxPBB: Infinity, takPBB: 3.027 },
];

/**
 * Alla 291 kommuner (inklusive Riksgenomsnitt) med deras skattesatser.
 * Sorterade alfabetiskt efter namn (Riksgenomsnitt först).
 */
export const KOMMUNER = [
  { namn: 'Riksgenomsnitt', skattesats: 32.38 },
  { namn: 'Ale', skattesats: 32.80 },
  { namn: 'Alingsås', skattesats: 32.84 },
  { namn: 'Alvesta', skattesats: 33.42 },
  { namn: 'Aneby', skattesats: 33.85 },
  { namn: 'Arboga', skattesats: 33.29 },
  { namn: 'Arjeplog', skattesats: 34.84 },
  { namn: 'Arvidsjaur', skattesats: 34.14 },
  { namn: 'Arvika', skattesats: 34.03 },
  { namn: 'Askersund', skattesats: 34.15 },
  { namn: 'Avesta', skattesats: 33.95 },
  { namn: 'Bengtsfors', skattesats: 34.40 },
  { namn: 'Berg', skattesats: 34.22 },
  { namn: 'Bjurholm', skattesats: 35.00 },
  { namn: 'Bjuv', skattesats: 32.17 },
  { namn: 'Boden', skattesats: 33.94 },
  { namn: 'Bollebygd', skattesats: 33.07 },
  { namn: 'Bollnäs', skattesats: 33.37 },
  { namn: 'Borgholm', skattesats: 33.44 },
  { namn: 'Borlänge', skattesats: 34.40 },
  { namn: 'Borås', skattesats: 32.79 },
  { namn: 'Botkyrka', skattesats: 32.23 },
  { namn: 'Boxholm', skattesats: 33.37 },
  { namn: 'Bromölla', skattesats: 33.74 },
  { namn: 'Bräcke', skattesats: 35.09 },
  { namn: 'Burlöv', skattesats: 31.27 },
  { namn: 'Båstad', skattesats: 31.41 },
  { namn: 'Dals-Ed', skattesats: 34.69 },
  { namn: 'Danderyd', skattesats: 30.58 },
  { namn: 'Degerfors', skattesats: 35.30 },
  { namn: 'Dorotea', skattesats: 35.65 },
  { namn: 'Eda', skattesats: 34.55 },
  { namn: 'Ekerö', skattesats: 31.45 },
  { namn: 'Eksjö', skattesats: 34.02 },
  { namn: 'Emmaboda', skattesats: 33.82 },
  { namn: 'Enköping', skattesats: 33.05 },
  { namn: 'Eskilstuna', skattesats: 32.85 },
  { namn: 'Eslöv', skattesats: 31.72 },
  { namn: 'Essunga', skattesats: 33.05 },
  { namn: 'Fagersta', skattesats: 32.99 },
  { namn: 'Falkenberg', skattesats: 32.50 },
  { namn: 'Falköping', skattesats: 33.43 },
  { namn: 'Falun', skattesats: 34.05 },
  { namn: 'Filipstad', skattesats: 34.55 },
  { namn: 'Finspång', skattesats: 33.70 },
  { namn: 'Flen', skattesats: 33.10 },
  { namn: 'Forshaga', skattesats: 34.63 },
  { namn: 'Färgelanda', skattesats: 34.39 },
  { namn: 'Gagnef', skattesats: 34.27 },
  { namn: 'Gislaved', skattesats: 33.75 },
  { namn: 'Gnesta', skattesats: 32.95 },
  { namn: 'Gnosjö', skattesats: 34.00 },
  { namn: 'Gotland', skattesats: 33.60 },
  { namn: 'Grums', skattesats: 34.78 },
  { namn: 'Grästorp', skattesats: 33.47 },
  { namn: 'Gullspång', skattesats: 33.97 },
  { namn: 'Gällivare', skattesats: 33.89 },
  { namn: 'Gävle', skattesats: 33.77 },
  { namn: 'Göteborg', skattesats: 32.60 },
  { namn: 'Götene', skattesats: 33.60 },
  { namn: 'Habo', skattesats: 33.93 },
  { namn: 'Hagfors', skattesats: 34.30 },
  { namn: 'Hallsberg', skattesats: 33.85 },
  { namn: 'Hallstahammar', skattesats: 32.69 },
  { namn: 'Halmstad', skattesats: 32.38 },
  { namn: 'Hammarö', skattesats: 35.05 },
  { namn: 'Haninge', skattesats: 31.28 },
  { namn: 'Haparanda', skattesats: 33.84 },
  { namn: 'Heby', skattesats: 34.21 },
  { namn: 'Hedemora', skattesats: 34.15 },
  { namn: 'Helsingborg', skattesats: 31.39 },
  { namn: 'Herrljunga', skattesats: 33.62 },
  { namn: 'Hjo', skattesats: 33.48 },
  { namn: 'Hofors', skattesats: 34.37 },
  { namn: 'Huddinge', skattesats: 31.71 },
  { namn: 'Hudiksvall', skattesats: 33.12 },
  { namn: 'Hultsfred', skattesats: 33.77 },
  { namn: 'Hylte', skattesats: 33.85 },
  { namn: 'Håbo', skattesats: 33.30 },
  { namn: 'Hällefors', skattesats: 34.35 },
  { namn: 'Härjedalen', skattesats: 34.17 },
  { namn: 'Härnösand', skattesats: 34.63 },
  { namn: 'Härryda', skattesats: 31.98 },
  { namn: 'Hässleholm', skattesats: 32.38 },
  { namn: 'Höganäs', skattesats: 30.91 },
  { namn: 'Högsby', skattesats: 34.07 },
  { namn: 'Hörby', skattesats: 32.26 },
  { namn: 'Höör', skattesats: 32.63 },
  { namn: 'Jokkmokk', skattesats: 34.29 },
  { namn: 'Järfälla', skattesats: 31.52 },
  { namn: 'Jönköping', skattesats: 33.40 },
  { namn: 'Kalix', skattesats: 33.89 },
  { namn: 'Kalmar', skattesats: 33.67 },
  { namn: 'Karlsborg', skattesats: 32.80 },
  { namn: 'Karlshamn', skattesats: 33.80 },
  { namn: 'Karlskoga', skattesats: 34.30 },
  { namn: 'Karlskrona', skattesats: 33.69 },
  { namn: 'Karlstad', skattesats: 33.55 },
  { namn: 'Katrineholm', skattesats: 32.95 },
  { namn: 'Kil', skattesats: 34.63 },
  { namn: 'Kinda', skattesats: 33.00 },
  { namn: 'Kiruna', skattesats: 34.39 },
  { namn: 'Klippan', skattesats: 31.93 },
  { namn: 'Knivsta', skattesats: 32.62 },
  { namn: 'Kramfors', skattesats: 34.43 },
  { namn: 'Kristianstad', skattesats: 32.64 },
  { namn: 'Kristinehamn', skattesats: 34.25 },
  { namn: 'Krokom', skattesats: 33.87 },
  { namn: 'Kumla', skattesats: 33.84 },
  { namn: 'Kungsbacka', skattesats: 32.58 },
  { namn: 'Kungsör', skattesats: 32.91 },
  { namn: 'Kungälv', skattesats: 32.92 },
  { namn: 'Kävlinge', skattesats: 29.59 },
  { namn: 'Köping', skattesats: 33.04 },
  { namn: 'Laholm', skattesats: 32.80 },
  { namn: 'Landskrona', skattesats: 31.42 },
  { namn: 'Laxå', skattesats: 35.00 },
  { namn: 'Lekeberg', skattesats: 33.73 },
  { namn: 'Leksand', skattesats: 33.80 },
  { namn: 'Lerum', skattesats: 32.03 },
  { namn: 'Lessebo', skattesats: 33.81 },
  { namn: 'Lidingö', skattesats: 29.67 },
  { namn: 'Lidköping', skattesats: 32.74 },
  { namn: 'Lilla Västby', skattesats: 33.85 },
  { namn: 'Lindesberg', skattesats: 34.60 },
  { namn: 'Linköping', skattesats: 31.75 },
  { namn: 'Ljungby', skattesats: 33.07 },
  { namn: 'Ljusdal', skattesats: 33.87 },
  { namn: 'Ljusnarsberg', skattesats: 33.80 },
  { namn: 'Lomma', skattesats: 30.72 },
  { namn: 'Ludvika', skattesats: 34.05 },
  { namn: 'Luleå', skattesats: 33.84 },
  { namn: 'Lund', skattesats: 32.42 },
  { namn: 'Lycksele', skattesats: 34.90 },
  { namn: 'Lysekil', skattesats: 33.94 },
  { namn: 'Malmö', skattesats: 32.42 },
  { namn: 'Malung-Sälen', skattesats: 34.45 },
  { namn: 'Malå', skattesats: 35.20 },
  { namn: 'Mariestad', skattesats: 32.74 },
  { namn: 'Mark', skattesats: 32.99 },
  { namn: 'Markaryd', skattesats: 33.31 },
  { namn: 'Mellerud', skattesats: 34.08 },
  { namn: 'Mjölby', skattesats: 33.45 },
  { namn: 'Mora', skattesats: 34.32 },
  { namn: 'Motala', skattesats: 33.25 },
  { namn: 'Mullsjö', skattesats: 34.10 },
  { namn: 'Munkedal', skattesats: 34.86 },
  { namn: 'Munkfors', skattesats: 34.30 },
  { namn: 'Mölndal', skattesats: 31.99 },
  { namn: 'Mönsterås', skattesats: 34.07 },
  { namn: 'Mörbylånga', skattesats: 34.07 },
  { namn: 'Nacka', skattesats: 30.11 },
  { namn: 'Nora', skattesats: 34.55 },
  { namn: 'Norberg', skattesats: 33.54 },
  { namn: 'Nordanstig', skattesats: 34.02 },
  { namn: 'Nordmaling', skattesats: 35.10 },
  { namn: 'Norrköping', skattesats: 33.30 },
  { namn: 'Norrtälje', skattesats: 32.05 },
  { namn: 'Norsjö', skattesats: 35.20 },
  { namn: 'Nybro', skattesats: 34.19 },
  { namn: 'Nykvarn', skattesats: 32.30 },
  { namn: 'Nyköping', skattesats: 32.25 },
  { namn: 'Nynäshamn', skattesats: 32.18 },
  { namn: 'Nässjö', skattesats: 34.30 },
  { namn: 'Ockelbo', skattesats: 34.27 },
  { namn: 'Olofström', skattesats: 33.75 },
  { namn: 'Orsa', skattesats: 34.30 },
  { namn: 'Orust', skattesats: 33.69 },
  { namn: 'Osby', skattesats: 33.99 },
  { namn: 'Oskarshamn', skattesats: 34.21 },
  { namn: 'Ovanåker', skattesats: 33.37 },
  { namn: 'Oxelösund', skattesats: 33.05 },
  { namn: 'Pajala', skattesats: 34.74 },
  { namn: 'Partille', skattesats: 31.36 },
  { namn: 'Perstorp', skattesats: 31.99 },
  { namn: 'Piteå', skattesats: 33.59 },
  { namn: 'Ragunda', skattesats: 34.92 },
  { namn: 'Robertsfors', skattesats: 35.00 },
  { namn: 'Ronneby', skattesats: 33.68 },
  { namn: 'Rättvik', skattesats: 33.80 },
  { namn: 'Sala', skattesats: 33.19 },
  { namn: 'Salem', skattesats: 32.00 },
  { namn: 'Sandviken', skattesats: 33.12 },
  { namn: 'Sigtuna', skattesats: 31.83 },
  { namn: 'Simrishamn', skattesats: 31.69 },
  { namn: 'Sjöbo', skattesats: 32.10 },
  { namn: 'Skara', skattesats: 33.38 },
  { namn: 'Skellefteå', skattesats: 34.45 },
  { namn: 'Skinnskatteberg', skattesats: 33.34 },
  { namn: 'Skurup', skattesats: 31.60 },
  { namn: 'Skövde', skattesats: 33.09 },
  { namn: 'Smedjebacken', skattesats: 34.44 },
  { namn: 'Sollefteå', skattesats: 34.68 },
  { namn: 'Sollentuna', skattesats: 30.45 },
  { namn: 'Solna', skattesats: 29.70 },
  { namn: 'Sorsele', skattesats: 35.45 },
  { namn: 'Sotenäs', skattesats: 33.47 },
  { namn: 'Staffanstorp', skattesats: 30.12 },
  { namn: 'Stenungsund', skattesats: 33.12 },
  { namn: 'Stockholm', skattesats: 30.55 },
  { namn: 'Storfors', skattesats: 34.98 },
  { namn: 'Storuman', skattesats: 34.95 },
  { namn: 'Strängnäs', skattesats: 32.50 },
  { namn: 'Strömstad', skattesats: 33.39 },
  { namn: 'Strömsund', skattesats: 34.92 },
  { namn: 'Sundbyberg', skattesats: 31.58 },
  { namn: 'Sundsvall', skattesats: 33.88 },
  { namn: 'Sunne', skattesats: 33.75 },
  { namn: 'Surahammar', skattesats: 33.19 },
  { namn: 'Svalöv', skattesats: 31.92 },
  { namn: 'Svedala', skattesats: 31.42 },
  { namn: 'Svenljunga', skattesats: 33.53 },
  { namn: 'Säffle', skattesats: 33.80 },
  { namn: 'Säter', skattesats: 34.30 },
  { namn: 'Sävsjö', skattesats: 33.68 },
  { namn: 'Söderhamn', skattesats: 33.17 },
  { namn: 'Söderköping', skattesats: 33.53 },
  { namn: 'Södertälje', skattesats: 32.38 },
  { namn: 'Sölvesborg', skattesats: 33.86 },
  { namn: 'Tanum', skattesats: 33.04 },
  { namn: 'Tibro', skattesats: 33.19 },
  { namn: 'Tidaholm', skattesats: 33.55 },
  { namn: 'Tierp', skattesats: 33.00 },
  { namn: 'Timrå', skattesats: 34.38 },
  { namn: 'Tingsryd', skattesats: 34.00 },
  { namn: 'Tjörn', skattesats: 33.19 },
  { namn: 'Tomelilla', skattesats: 31.79 },
  { namn: 'Torsby', skattesats: 34.30 },
  { namn: 'Torsås', skattesats: 33.79 },
  { namn: 'Tranemo', skattesats: 32.98 },
  { namn: 'Tranås', skattesats: 33.77 },
  { namn: 'Trelleborg', skattesats: 31.58 },
  { namn: 'Trollhättan', skattesats: 33.84 },
  { namn: 'Trosa', skattesats: 32.03 },
  { namn: 'Tyresö', skattesats: 31.83 },
  { namn: 'Täby', skattesats: 29.88 },
  { namn: 'Töreboda', skattesats: 33.20 },
  { namn: 'Uddevalla', skattesats: 33.64 },
  { namn: 'Ulricehamn', skattesats: 32.53 },
  { namn: 'Umeå', skattesats: 34.65 },
  { namn: 'Upplands Västby', skattesats: 31.75 },
  { namn: 'Upplands-Bro', skattesats: 31.73 },
  { namn: 'Uppsala', skattesats: 32.85 },
  { namn: 'Uppvidinge', skattesats: 33.80 },
  { namn: 'Vadstena', skattesats: 34.35 },
  { namn: 'Vaggeryd', skattesats: 33.25 },
  { namn: 'Valdemarsvik', skattesats: 34.03 },
  { namn: 'Vallentuna', skattesats: 31.23 },
  { namn: 'Vansbro', skattesats: 34.28 },
  { namn: 'Vara', skattesats: 33.25 },
  { namn: 'Varberg', skattesats: 31.73 },
  { namn: 'Vaxholm', skattesats: 31.63 },
  { namn: 'Vellinge', skattesats: 29.68 },
  { namn: 'Vetlanda', skattesats: 33.77 },
  { namn: 'Vilhelmina', skattesats: 35.50 },
  { namn: 'Vimmerby', skattesats: 34.22 },
  { namn: 'Vindeln', skattesats: 35.20 },
  { namn: 'Vingåker', skattesats: 33.50 },
  { namn: 'Vårgårda', skattesats: 33.09 },
  { namn: 'Vänersborg', skattesats: 33.69 },
  { namn: 'Vännäs', skattesats: 35.20 },
  { namn: 'Värmdö', skattesats: 31.31 },
  { namn: 'Värnamo', skattesats: 33.28 },
  { namn: 'Västervik', skattesats: 33.02 },
  { namn: 'Västerås', skattesats: 31.24 },
  { namn: 'Växjö', skattesats: 32.19 },
  { namn: 'Ydre', skattesats: 34.10 },
  { namn: 'Ystad', skattesats: 31.29 },
  { namn: 'Åmål', skattesats: 33.94 },
  { namn: 'Ånge', skattesats: 34.62 },
  { namn: 'Åre', skattesats: 33.92 },
  { namn: 'Årjäng', skattesats: 34.25 },
  { namn: 'Åsele', skattesats: 35.45 },
  { namn: 'Åstorp', skattesats: 31.47 },
  { namn: 'Åtvidaberg', skattesats: 33.94 },
  { namn: 'Älmhult', skattesats: 33.86 },
  { namn: 'Älvdalen', skattesats: 34.77 },
  { namn: 'Älvkarleby', skattesats: 34.40 },
  { namn: 'Älvsbyn', skattesats: 33.79 },
  { namn: 'Ängelholm', skattesats: 31.35 },
  { namn: 'Öckerö', skattesats: 33.04 },
  { namn: 'Ödeshög', skattesats: 33.95 },
  { namn: 'Örebro', skattesats: 33.65 },
  { namn: 'Örkelljunga', skattesats: 30.24 },
  { namn: 'Örnsköldsvik', skattesats: 33.85 },
  { namn: 'Östersund', skattesats: 33.72 },
  { namn: 'Österåker', skattesats: 28.93 },
  { namn: 'Östhammar', skattesats: 33.30 },
  { namn: 'Östra Västby', skattesats: 32.17 },
  { namn: 'Överkalix', skattesats: 34.14 },
  { namn: 'Övertorneå', skattesats: 33.84 },
];

/**
 * Kommuner som kvalificerar för regional skattereduktion för boende.
 * Buggfix: originalet hade "Filipstads" men rullgardinsmenyn har "Filipstad".
 */
export const KOMMUNER_MED_REGIONAL_SKATTEREDUKTION = new Set([
  'Avesta', 'Gagnef', 'Hedemora', 'Leksand', 'Ludvika', 'Malung-Sälen',
  'Mora', 'Orsa', 'Rättvik', 'Smedjebacken', 'Säter', 'Vansbro', 'Älvdalen',
  'Bollnäs', 'Hudiksvall', 'Ljusdal', 'Nordanstig', 'Ockelbo', 'Ovanåker', 'Söderhamn',
  'Berg', 'Bräcke', 'Härjedalen', 'Krokom', 'Ragunda', 'Strömsund', 'Åre', 'Östersund',
  'Arjeplog', 'Arvidsjaur', 'Boden', 'Gällivare', 'Haparanda', 'Jokkmokk', 'Kalix',
  'Kiruna', 'Pajala', 'Piteå', 'Älvsbyn', 'Överkalix', 'Övertorneå',
  'Arvika', 'Eda', 'Filipstad', 'Hagfors', 'Munkfors', 'Storfors', 'Sunne', 'Säffle',
  'Torsby', 'Årjäng',
  'Bjurholm', 'Dorotea', 'Lycksele', 'Malå', 'Nordmaling', 'Norsjö', 'Robertsfors',
  'Skellefteå', 'Sorsele', 'Storuman', 'Vilhelmina', 'Vindeln', 'Vännäs', 'Åsele',
  'Härnösand', 'Kramfors', 'Sollefteå', 'Timrå', 'Ånge', 'Örnsköldsvik',
  'Bengtsfors', 'Dals-Ed', 'Färgelanda', 'Mellerud', 'Åmål',
]);
